import Head from "next/head";

import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Collections from "@/components/Collections";
import Slider from "@/components/Slider";
import Auction from "@/components/Auction";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <div className="scroll-smooth overflow-hidden select-none">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <Collections />
      <Auction />
      <Footer />
    </div>
  );
}
